// NASCLA Tennessee General Contractor Testing Bundle — Reference Book Catalog
// Each book maps to a domain-specific trade tag and knowledge domains.
// Questions generated from these books are tagged with BOTH "Tennessee General Contractor"
// and the domain trade (comma-separated) so they surface in both filtered views.

export const NASCLA_BOOKS = [
  {
    id: 'roofing',
    title: 'Roofing Construction & Estimating (Revised)',
    author: 'Daniel Atcheson',
    tradeTag: 'Roofer',
    knowledgeDomain: 'Roofing',
    lawType: 'knowledge',
    jurisdiction: 'Tennessee',
    topics: [
      'roofing materials and selection',
      'roof framing and sheathing',
      'underlayment and ice and water shield',
      'flashing details for valleys, chimneys, and penetrations',
      'asphalt shingle installation patterns and nailing',
      'steep-slope vs low-slope roofing systems',
      'roof estimating: squares, waste factors, and labor',
      'roof ventilation requirements',
      'drip edge installation',
      'roof inspection and common defects',
      'safety on steep roofs and fall protection',
    ],
  },
  {
    id: 'pipe-excavation',
    title: 'Pipe and Excavation Contracting',
    author: 'Dave Roberts, revised by Dan Atcheson',
    tradeTag: 'Plumber',
    knowledgeDomain: 'Excavation and Earthwork',
    lawType: 'knowledge',
    jurisdiction: 'Tennessee',
    topics: [
      'trenching safety and OSHA excavation standards',
      'soil classification and trench stability',
      'shoring, shielding, and sloping systems',
      'trench boxes and trench safety',
      'sewer line installation and testing',
      'water line installation and pressure testing',
      'pipe materials: PVC, HDPE, ductile iron, concrete',
      'pipe bedding and haunching',
      'backfilling and compaction methods',
      'excavation equipment selection',
      'grade control and laser leveling',
      'utility location and Tennessee One-Call 811',
    ],
  },
  {
    id: 'irc2018',
    title: '2018 IRC (International Residential Code) for One- and Two-Family Dwellings',
    author: 'International Code Council (ICC)',
    tradeTag: 'Building Contractor',
    knowledgeDomain: 'Building Codes',
    lawType: 'regulation',
    jurisdiction: 'Tennessee',
    topics: [
      'IRC 2018 building planning and construction',
      'foundation requirements and anchor bolts',
      'floor framing: joists, spans, and blocking',
      'wall framing: stud sizes, spacing, and headers',
      'roof framing: rafters, trusses, and ceiling joists',
      'egress requirements for doors and emergency escape windows',
      'fire-rated assemblies and fire blocking',
      'stair and ramp requirements: rise, run, headroom',
      'energy efficiency and insulation requirements',
      'mechanical, fuel gas, and plumbing provisions in the IRC',
      'Tennessee amendments to the 2018 IRC',
      'deck construction and guard requirements',
    ],
  },
  {
    id: 'masonry',
    title: 'Modern Masonry (10th Edition)',
    author: 'C. F. Kreh',
    tradeTag: 'Mason',
    knowledgeDomain: 'Concrete and Masonry',
    lawType: 'knowledge',
    jurisdiction: 'Tennessee',
    topics: [
      'brick, block, stone, and concrete masonry units',
      'mortar types: M, S, N, O and their applications',
      'masonry bonds: running, Flemish, English, stack',
      'flashing and weep holes in masonry walls',
      'masonry wall types: veneer, solid, cavity',
      'reinforcement and joint reinforcement',
      'masonry foundations and piers',
      'cold and hot weather masonry construction',
      'masonry standards and ASTM specifications',
      'cleaning and repairing masonry',
      'estimating masonry materials',
    ],
  },
  {
    id: 'concrete',
    title: "The Contractor's Guide to Quality Concrete Construction (4th Edition)",
    author: 'ACI/ASCC',
    tradeTag: 'Concrete Contractor',
    knowledgeDomain: 'Concrete and Masonry',
    lawType: 'knowledge',
    jurisdiction: 'Tennessee',
    topics: [
      'concrete mix design and proportions',
      'concrete placing methods and consolidation',
      'concrete finishing techniques and timing',
      'curing methods and their importance',
      'formwork design and removal',
      'reinforcement: rebar, wire mesh, and placement',
      'concrete testing: slump, air content, compressive strength',
      'concrete defects: cracking, scaling, honeycombing, spalling',
      'jointing: control joints, expansion joints, construction joints',
      'ACI standards for concrete construction',
      'hot and cold weather concreting',
      'concrete slab on grade construction',
    ],
  },
  {
    id: 'carpentry',
    title: 'Carpentry & Building Construction',
    author: 'William M. Perkinson et al.',
    tradeTag: 'Carpenter',
    knowledgeDomain: 'Structural and Framing',
    lawType: 'knowledge',
    jurisdiction: 'Tennessee',
    topics: [
      'floor framing: sills, joists, subflooring',
      'wall framing: plates, studs, headers, rough openings',
      'roof framing: rafters, trusses, ridge, collar ties',
      'stair construction: stringers, treads, risers, headroom',
      'door and window installation',
      'exterior and interior finish carpentry',
      'wood properties and lumber grading',
      'engineered wood products: LVL, glulam, I-joists',
      'fasteners and connectors',
      'insulation and air sealing',
      'reading construction drawings and plans',
      'estimating materials for carpentry projects',
    ],
  },
  {
    id: 'nascla-biz-law',
    title: 'NASCLA Contractors Guide to Business, Law and Project Management (Tennessee, 3rd Edition)',
    author: 'NASCLA',
    tradeTag: 'Project Manager',
    knowledgeDomain: 'Licensing and Business Management',
    lawType: 'statute',
    jurisdiction: 'Tennessee',
    topics: [
      'Tennessee contractor license requirements (TCA 62-6-101)',
      'license classifications and monetary limits',
      'bond and insurance requirements',
      'business organization types: sole proprietor, LLC, corporation',
      'Tennessee tax registration and sales tax',
      'contracts: elements, types, and Tennessee requirements',
      'mechanics lien law and filing deadlines',
      'project management and scheduling',
      'estimating and bidding',
      'payroll and employment law basics',
      'safety management and OSHA compliance',
      'financial management and accounting basics',
    ],
  },
  {
    id: 'gypsum',
    title: 'The Gypsum Construction Handbook (Seventh Edition)',
    author: 'USG',
    tradeTag: 'Drywall Contractor',
    knowledgeDomain: 'Drywall and Gypsum',
    lawType: 'knowledge',
    jurisdiction: 'Tennessee',
    topics: [
      'gypsum board types: regular, fire-rated, moisture-resistant',
      'drywall installation and fastening patterns',
      'joint treatment: taping, mudding, sanding',
      'finishing levels 1-5 and their specifications',
      'fire-rated assemblies and UL ratings',
      'metal framing: studs, track, and furring',
      'acoustical ceiling systems and grid layouts',
      'plaster application and lath',
      'moisture and mold prevention',
      'drywall estimating and waste factors',
      'corner bead and trim installation',
    ],
  },
  {
    id: 'osha1926',
    title: '1926 OSHA Construction Industry Regulations & Standards (January 2024)',
    author: 'Mancomm',
    tradeTag: 'Construction Safety',
    knowledgeDomain: 'Safety and Health',
    lawType: 'regulation',
    jurisdiction: 'Federal',
    topics: [
      'OSHA 29 CFR 1926 general safety and health provisions',
      'fall protection: trigger heights, guardrails, PFAS, safety nets',
      'scaffolding: types, load capacity, inspection, and fall protection',
      'excavation safety: sloping, shoring, shielding, and daily inspections',
      'stairways and ladders: requirements and safe use',
      'PPE: hard hats, eye protection, hearing protection, and foot protection',
      'hazard communication and chemical safety',
      'electrical safety: GFCI, grounding, and temporary wiring',
      'fire protection and prevention on construction sites',
      'crane and rigging safety',
      'OSHA recordkeeping: 300 logs, 300A summaries, and reporting',
      'competent person requirements and responsibilities',
    ],
  },
];