// Master list of all licensed professions at state and federal levels

export const TRADES = [

  // ── Construction: General ─────────────────────────────────────────────────
  "General Contractor",
  "Building Contractor",
  "Residential Builder",
  "Commercial Builder",
  "Remodeling Contractor",
  "Owner-Builder",

  // ── Construction: Plumbing & Piping ──────────────────────────────────────
  "Plumber",
  "Master Plumber",
  "Journeyman Plumber",
  "Pipefitter",
  "Steamfitter",
  "Sprinkler Fitter",
  "Medical Gas Installer",
  "Backflow Prevention Technician",

  // ── Construction: Electrical ─────────────────────────────────────────────
  "Electrician",
  "Master Electrician",
  "Journeyman Electrician",
  "Residential Electrician",
  "Commercial Electrician",
  "Industrial Electrician",
  "Lineman",
  "Inside Wireman",
  "Low Voltage Technician",
  "Fire Alarm Technician",
  "Security Alarm Installer",
  "Telecommunications Installer",
  "Solar Photovoltaic Installer",
  "Wind Turbine Technician",

  // ── Construction: HVAC & Refrigeration ───────────────────────────────────
  "HVAC Technician",
  "HVAC Contractor",
  "Air Conditioning Contractor",
  "Heating Contractor",
  "Refrigeration Technician",
  "Commercial Refrigeration Technician",
  "Boiler Operator",
  "Boiler Installer",
  "Mechanical Contractor",

  // ── Construction: Structural Trades ──────────────────────────────────────
  "Carpenter",
  "Rough Carpenter",
  "Finish Carpenter",
  "Cabinet Maker",
  "Millwork Installer",
  "Framer",
  "Concrete Contractor",
  "Concrete Finisher",
  "Mason",
  "Bricklayer",
  "Block Mason",
  "Stone Mason",
  "Tile Setter",
  "Marble Setter",
  "Terrazzo Worker",
  "Plasterer",
  "Stucco Contractor",
  "Drywall Installer",
  "Drywall Finisher",
  "Lather",

  // ── Construction: Exterior & Roofing ─────────────────────────────────────
  "Roofer",
  "Roofing Contractor",
  "Sheet Metal Worker",
  "Siding Installer",
  "Gutter Installer",
  "Waterproofing Contractor",
  "Caulking Contractor",
  "Glazier",
  "Window Installer",
  "Door Installer",

  // ── Construction: Finishing Trades ───────────────────────────────────────
  "Painter",
  "Painting Contractor",
  "Wallpaper Hanger",
  "Decorator",
  "Flooring Installer",
  "Hardwood Floor Installer",
  "Carpet Installer",
  "Vinyl Floor Installer",
  "Epoxy Floor Installer",

  // ── Construction: Insulation & Weatherization ────────────────────────────
  "Insulation Contractor",
  "Spray Foam Insulator",
  "Weatherization Specialist",
  "Energy Auditor",
  "Energy Code Inspector",

  // ── Construction: Welding & Metal ────────────────────────────────────────
  "Welder",
  "Certified Welder",
  "Pipefitter-Welder",
  "Structural Welder",
  "Ironworker",
  "Reinforcing Ironworker",
  "Ornamental Ironworker",
  "Structural Steel Erector",
  "Metal Building Assembler",

  // ── Construction: Demolition & Excavation ────────────────────────────────
  "Demolition Contractor",
  "Excavation Contractor",
  "Grading Contractor",
  "Trenching Contractor",
  "Site Work Contractor",
  "Earthmoving Contractor",

  // ── Construction: Heavy Equipment ────────────────────────────────────────
  "Heavy Equipment Operator",
  "Crane Operator",
  "Tower Crane Operator",
  "Rigger",
  "Hoist Operator",
  "Forklift Operator",
  "Pile Driver Operator",

  // ── Construction: Specialty ───────────────────────────────────────────────
  "Elevator Mechanic",
  "Elevator Installer",
  "Escalator Mechanic",
  "Asbestos Abatement Contractor",
  "Lead Abatement Contractor",
  "Mold Remediation Contractor",
  "Fire Sprinkler Installer",
  "Fire Suppression Contractor",
  "Kitchen Hood System Installer",
  "Swimming Pool Contractor",
  "Spa & Hot Tub Installer",
  "Fence Contractor",
  "Dock Builder",
  "Marina Contractor",
  "Well Driller",
  "Well Pump Installer",
  "Irrigation Contractor",
  "Lawn Sprinkler Installer",
  "Sign Contractor",
  "Awning Installer",

  // ── Septic & Wastewater ───────────────────────────────────────────────────
  "Septic System Installer",
  "Septic Tank Installer",
  "Septic System Designer",
  "Septic System Pumper",
  "Septic System Inspector",
  "Wastewater Treatment Operator",
  "Wastewater Facility Operator",
  "On-Site Wastewater Installer",

  // ── Drainage & Site Water Management ─────────────────────────────────────
  "Drainage Contractor",
  "Underground Drainage Contractor",
  "Surface Drainage Contractor",
  "Stormwater Drainage Contractor",
  "French Drain Installer",
  "Catch Basin Installer",
  "Culvert Installer",
  "Waterway & Channel Contractor",
  "Erosion Control Contractor",
  "Sediment Control Contractor",
  "Stormwater BMP Installer",
  "Sump Pump Installer",
  "Drainage System Designer",

  // ── Retaining Walls & Earthwork Structures ────────────────────────────────
  "Retaining Wall Contractor",
  "Segmental Retaining Wall Installer",
  "Concrete Retaining Wall Contractor",
  "Timber Retaining Wall Installer",
  "Gabion Wall Installer",
  "Soldier Pile & Lagging Contractor",
  "Sheet Pile Contractor",
  "Geo-Grid & MSE Wall Contractor",

  // ── Hardscaping & Paving ──────────────────────────────────────────────────
  "Hardscaping Contractor",
  "Paver Installer",
  "Interlocking Concrete Paver Installer",
  "Natural Stone Paver Installer",
  "Permeable Paver Installer",
  "Patio & Walkway Contractor",
  "Driveway Contractor",
  "Asphalt Paving Contractor",
  "Stamped Concrete Contractor",
  "Outdoor Structure Contractor",
  "Pergola & Arbor Installer",
  "Outdoor Kitchen Contractor",
  "Fire Pit & Fireplace Contractor",
  "Decorative Concrete Contractor",

  // ── Landscaping & Horticulture ────────────────────────────────────────────
  "Landscape Contractor",
  "Landscape Architect",
  "Landscape Designer",
  "Arborist",
  "Certified Arborist",
  "Tree Trimmer",
  "Tree Service Operator",
  "Pesticide Applicator",
  "Pesticide Dealer",
  "Lawn Care Operator",
  "Turf Management Specialist",
  "Golf Course Superintendent",
  "Nursery Operator",
  "Florist",
  "Interior Plantscaper",

  // ── Design & Engineering ──────────────────────────────────────────────────
  "Architect",
  "Landscape Architect",
  "Interior Designer",
  "Industrial Designer",
  "Professional Engineer",
  "Structural Engineer",
  "Civil Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Chemical Engineer",
  "Environmental Engineer",
  "Fire Protection Engineer",
  "Geotechnical Engineer",
  "Land Surveyor",
  "Professional Land Surveyor",
  "Photogrammetrist",
  "Geologist",
  "Soil Scientist",
  "Hydrologist",
  "Geophysicist",

  // ── Inspection & Code Enforcement ────────────────────────────────────────
  "Home Inspector",
  "Building Inspector",
  "Code Enforcement Officer",
  "Plans Examiner",
  "Structural Inspector",
  "Roofing Inspector",
  "Electrical Inspector",
  "Plumbing Inspector",
  "Mechanical Inspector",
  "Fire Inspector",
  "Elevator Inspector",
  "Environmental Inspector",
  "Asbestos Inspector",
  "Lead Inspector",
  "Mold Inspector",
  "Radon Measurement Technician",
  "Non-Destructive Testing Technician",

  // ── Real Estate & Finance ─────────────────────────────────────────────────
  "Real Estate Agent",
  "Real Estate Broker",
  "Real Estate Appraiser",
  "Property Manager",
  "Community Association Manager",
  "Mortgage Broker",
  "Mortgage Loan Originator",
  "Title Examiner",
  "Escrow Agent",
  "Auctioneer",
  "Real Estate Auctioneer",

  // ── Accounting & Financial Services ──────────────────────────────────────
  "Accountant",
  "Accountant - CPA (Certified Public Accountant)",
  "Accountant - Management Accountant (Cost / Staff / Industrial)",
  "Accountant - Chartered Accountant (CA)",
  "Accountant - Auditor (Internal)",
  "Accountant - Auditor (External)",
  "Accountant - Forensic Accountant",
  "Accountant - Government Accountant",
  "Accountant - Investment Accountant",
  "Accountant - Project Accountant",
  "Accountant - Tax Examiner / Tax Accountant",
  "Accountant - Enrolled Agent",
  "Accountant - Bookkeeper",
  "Accountant - Payroll Specialist",
  "Accountant - Fund / Nonprofit Accountant",
  "Accountant - Financial Advisor (Accounting scope)",
  "Financial Advisor",
  "Investment Advisor",
  "Securities Broker",
  "Insurance Agent",
  "Insurance Broker",
  "Public Adjuster",
  "Surplus Lines Broker",
  "Bail Bondsman",
  "Debt Collector",
  "Debt Management Counselor",
  "Mortgage Servicer",
  "Check Casher",
  "Money Transmitter",
  "Currency Exchange Operator",
  "Pawnbroker",
  "Precious Metals Dealer",
  "Scrap Metal Dealer",
  "Court Reporter",
  "Notary Public",
  "Immigration Consultant",
  "Process Server",

  // ── Attorney / Lawyer — Parent + Practice Area Categories ────────────────
  "Attorney / Lawyer",

  // Criminal Law
  "Attorney - Criminal Law",
  "Attorney - Criminal Law - Criminal Defense",
  "Attorney - Criminal Law - Prosecution / District Attorney",
  "Attorney - Criminal Law - White Collar Crime",
  "Attorney - Criminal Law - Juvenile Criminal",
  "Attorney - Criminal Law - DUI / Traffic Offense",

  // Civil Litigation
  "Attorney - Civil Litigation",
  "Attorney - Civil Litigation - Personal Injury / Tort",
  "Attorney - Civil Litigation - Class Action",
  "Attorney - Civil Litigation - Commercial Litigation",
  "Attorney - Civil Litigation - Civil Rights",
  "Attorney - Civil Litigation - Medical Malpractice",
  "Attorney - Civil Litigation - Product Liability",

  // Family Law
  "Attorney - Family Law",
  "Attorney - Family Law - Divorce & Dissolution",
  "Attorney - Family Law - Child Custody & Support",
  "Attorney - Family Law - Adoption",
  "Attorney - Family Law - Domestic Violence",
  "Attorney - Family Law - Guardianship & Conservatorship",
  "Attorney - Family Law - Prenuptial Agreements",

  // Corporate & Business Law
  "Attorney - Corporate & Business Law",
  "Attorney - Corporate & Business Law - Business Formation & Governance",
  "Attorney - Corporate & Business Law - Mergers & Acquisitions",
  "Attorney - Corporate & Business Law - Contract Law",
  "Attorney - Corporate & Business Law - Franchise Law",
  "Attorney - Corporate & Business Law - Securities & Finance",
  "Attorney - Corporate & Business Law - Bankruptcy Law",
  "Attorney - Corporate & Business Law - Commercial Law",

  // Property & Real Estate Law
  "Attorney - Property & Real Estate Law",
  "Attorney - Property & Real Estate Law - Residential Real Estate",
  "Attorney - Property & Real Estate Law - Commercial Real Estate",
  "Attorney - Property & Real Estate Law - Landlord-Tenant",
  "Attorney - Property & Real Estate Law - Eminent Domain / Condemnation",
  "Attorney - Property & Real Estate Law - Construction Defect",
  "Attorney - Property & Real Estate Law - Zoning & Land Use",

  // Estate Planning & Probate Law
  "Attorney - Estate Planning & Probate Law",
  "Attorney - Estate Planning & Probate Law - Wills & Trusts",
  "Attorney - Estate Planning & Probate Law - Probate Administration",
  "Attorney - Estate Planning & Probate Law - Elder Law",
  "Attorney - Estate Planning & Probate Law - Special Needs Planning",
  "Attorney - Estate Planning & Probate Law - Asset Protection",

  // Administrative & Regulatory Law
  "Attorney - Administrative & Regulatory Law",
  "Attorney - Administrative & Regulatory Law - Environmental Law",
  "Attorney - Administrative & Regulatory Law - Healthcare Regulatory",
  "Attorney - Administrative & Regulatory Law - Immigration Law",
  "Attorney - Administrative & Regulatory Law - Labor & Employment Law",
  "Attorney - Administrative & Regulatory Law - Government Contracts",
  "Attorney - Administrative & Regulatory Law - Education Law",
  "Attorney - Administrative & Regulatory Law - Tax Law",

  // Intellectual Property Law
  "Attorney - Intellectual Property Law",
  "Attorney - Intellectual Property Law - Patent Law",
  "Attorney - Intellectual Property Law - Trademark Law",
  "Attorney - Intellectual Property Law - Copyright Law",
  "Attorney - Intellectual Property Law - Trade Secret Law",
  "Attorney - Intellectual Property Law - Entertainment & Media Law",
  "Attorney - Intellectual Property Law - Cybersecurity & Data Privacy Law",

  // Additional major practice areas from Clio source
  "Attorney - Defense Law (Civil & Criminal)",
  "Attorney - Health Care Law",
  "Attorney - Insurance Law",
  "Attorney - International Law",
  "Attorney - Sports & Entertainment Law",
  "Attorney - Military Law / JAG",
  "Attorney - Workers' Compensation Law",
  "Attorney - Social Security Disability Law",
  "Attorney - Cannabis Law",
  "Attorney - Animal Law",

  // ── Automotive & Transportation ───────────────────────────────────────────
  "Auto Mechanic",
  "Automotive Technician",
  "Diesel Mechanic",
  "Heavy Truck Mechanic",
  "Auto Body Repair Technician",
  "Collision Repair Technician",
  "Paint & Body Specialist",
  "Transmission Specialist",
  "Brake Specialist",
  "Emissions Inspector",
  "Vehicle Safety Inspector",
  "Smog Technician",
  "Tire Technician",
  "Auto Glass Technician",
  "Automotive Locksmith",
  "Locksmith",
  "Towing Operator",
  "Vehicle Towing Service",
  "Driving Instructor",
  "CDL Instructor",
  "Motorcycle Mechanic",
  "Motorcycle Dealer",
  "Used Car Dealer",
  "New Car Dealer",
  "Auto Auction Operator",
  "Vehicle Dismantler",
  "Salvage Vehicle Dealer",

  // ── Commercial Driving & Trucking ─────────────────────────────────────────
  "Commercial Driver (CDL)",
  "Truck Driver",
  "Hazardous Materials Driver",
  "Tanker Driver",
  "Double/Triple Trailer Driver",
  "Passenger Bus Driver",
  "School Bus Driver",
  "Limousine Driver",
  "Taxi Driver",
  "Rideshare Driver",
  "Paratransit Driver",
  "Motor Carrier Operator",
  "Freight Broker",
  "Transportation Broker",

  // ── Aviation ──────────────────────────────────────────────────────────────
  "Student Pilot",
  "Private Pilot",
  "Instrument-Rated Pilot",
  "Commercial Pilot",
  "Airline Transport Pilot (ATP)",
  "Flight Instructor (CFI)",
  "Instrument Flight Instructor (CFII)",
  "Multi-Engine Instructor (MEI)",
  "Sport Pilot",
  "Recreational Pilot",
  "Helicopter Pilot",
  "Gyroplane Pilot",
  "Glider Pilot",
  "Balloon Pilot",
  "Airship Pilot",
  "Seaplane Pilot",
  "Air Traffic Controller",
  "Aircraft Dispatcher",
  "Aircraft Mechanic (A&P)",
  "Aviation Maintenance Technician",
  "Avionics Technician",
  "Parachute Rigger",
  "Drone Operator (Part 107 Remote Pilot)",
  "Drone Operator (Recreational)",
  "Agricultural Drone Operator",
  "UAS Commercial Operator",
  "Hot Air Balloon Operator",
  "Ultralight Vehicle Operator",
  "Air Tour Operator",
  "Part 135 Charter Operator",
  "Part 121 Airline Operator",

  // ── Maritime & Marine ─────────────────────────────────────────────────────
  "Boat Captain",
  "Charter Boat Captain",
  "Master Mariner",
  "Merchant Marine Officer",
  "Mate (Deck Officer)",
  "Marine Engineer",
  "Chief Engineer (Vessel)",
  "USCG Licensed Captain (6-Pack)",
  "Inland Waters Captain",
  "Near Coastal Captain",
  "Towing Vessel Operator",
  "Passenger Vessel Operator",
  "Ferry Operator",
  "Dredging Operator",
  "Port Pilot",
  "Marine Surveyor",
  "Commercial Fisherman",
  "Fishing Vessel Operator",
  "Fish Dealer",
  "Shellfish Harvester",
  "Aquaculture Operator",
  "Scuba Diving Instructor",
  "Commercial Diver",
  "Underwater Welder",
  "Marine Mechanic",
  "Boat Dealer",
  "Marina Operator",
  "Water Taxi Operator",

  // ── Railroad & Transit ────────────────────────────────────────────────────
  "Locomotive Engineer",
  "Train Conductor",
  "Railroad Signal Maintainer",
  "Railroad Track Inspector",
  "Transit Operator",
  "Light Rail Operator",
  "Subway Operator",

  // ── Agriculture & Farming ─────────────────────────────────────────────────
  "Farmer",
  "Crop Farmer",
  "Livestock Farmer",
  "Poultry Farmer",
  "Organic Farmer",
  "Hemp Farmer",
  "Cannabis Cultivator",
  "Grain Dealer",
  "Cotton Gin Operator",
  "Agricultural Cooperative Manager",
  "Farm Labor Contractor",
  "Crop Insurance Adjuster",
  "Agricultural Consultant",
  "Certified Crop Adviser",
  "Soil and Water Conservation Technician",
  "Irrigation System Designer",

  // ── Dairy & Animal Products ───────────────────────────────────────────────
  "Dairy Producer",
  "Dairy Farmer",
  "Milk Handler",
  "Cheese Maker",
  "Butter Maker",
  "Dairy Plant Operator",
  "Grade A Dairy Inspector",
  "Egg Grader",
  "Poultry Processor",
  "Honey Producer",
  "Beekeeper",
  "Mead Producer",

  // ── Meat & Slaughter ──────────────────────────────────────────────────────
  "Meat Inspector",
  "USDA Meat Grader",
  "Slaughterhouse Operator",
  "Meat Packer",
  "Meat Cutter",
  "Butcher",
  "Custom Exempt Slaughterer",
  "Poultry Slaughterer",
  "Wild Game Processor",
  "Seafood Processor",
  "Seafood Handler",
  "Cold Storage Operator",

  // ── Food & Beverage Production ────────────────────────────────────────────
  "Food Service Manager",
  "Food Handler",
  "Food Safety Manager",
  "Certified Food Manager",
  "Mobile Food Vendor",
  "Catering Operator",
  "Food Truck Operator",
  "Commissary Kitchen Operator",
  "Bakery Operator",
  "Candy Manufacturer",
  "Cottage Food Operator",
  "Alcohol Server",
  "Bartender",
  "Brewmaster",
  "Craft Brewery Operator",
  "Winery Operator",
  "Distillery Operator",
  "Cidery Operator",
  "Mead Winery Operator",
  "Liquor Store Operator",
  "Beer Distributor",
  "Wine Distributor",
  "Spirits Distributor",
  "Alcohol Importer",
  "Tobacco Retailer",
  "Tobacco Distributor",
  "Tobacco Manufacturer",
  "E-Cigarette Retailer",
  "Cannabis Dispensary Operator",
  "Cannabis Processor",
  "Cannabis Delivery Driver",

  // ── Health & Medical ──────────────────────────────────────────────────────
  "Physician",
  "Osteopathic Physician",
  "Surgeon",
  "Physician Assistant",
  "Nurse Practitioner",
  "Registered Nurse",
  "Licensed Practical Nurse",
  "Certified Nursing Assistant",
  "Home Health Aide",
  "Personal Care Aide",
  "Nursing Home Administrator",
  "Assisted Living Administrator",
  "Adult Day Care Operator",
  "Hospice Administrator",
  "Dentist",
  "Dental Hygienist",
  "Dental Assistant",
  "Orthodontist",
  "Oral Surgeon",
  "Pharmacist",
  "Pharmacy Technician",
  "Pharmacy Intern",
  "Optometrist",
  "Optician",
  "Ophthalmologist",
  "Audiologist",
  "Hearing Aid Dealer",
  "Speech-Language Pathologist",
  "Occupational Therapist",
  "Physical Therapist",
  "Physical Therapy Assistant",
  "Chiropractor",
  "Podiatrist",
  // ── Naturopathic Medicine ─────────────────────────────────────────────────
  "Naturopathic Doctor",
  "Naturopathic Doctor - General Naturopathic Practice",
  "Naturopathic Doctor - Naturopathic Oncology",
  "Naturopathic Doctor - Naturopathic Pediatrics",
  "Naturopathic Doctor - Naturopathic Cardiology",
  "Naturopathic Doctor - Naturopathic Endocrinology",
  "Naturopathic Doctor - Naturopathic Gastroenterology",
  "Naturopathic Doctor - Naturopathic Minor Surgery",
  "Naturopathic Doctor - Botanical / Herbal Medicine",
  "Naturopathic Doctor - Homeopathy (ND scope)",
  "Naturopathic Doctor - Clinical Nutrition (ND scope)",
  "Naturopathic Doctor - Physical Medicine (ND scope)",

  // ── Homeopathic Medicine ──────────────────────────────────────────────────
  "Homeopathic Practitioner",
  "Homeopathic Practitioner - Classical Homeopathy",
  "Homeopathic Practitioner - Clinical Homeopathy",
  "Homeopathic Practitioner - Homeopathic Physician (MD/DO with homeopathy)",
  "Homeopathic Practitioner - Veterinary Homeopathy",
  "Homeopathic Practitioner - Homeopathic Pharmacy",

  // ── Holistic Health ───────────────────────────────────────────────────────
  "Holistic Health Practitioner",
  "Holistic Health Practitioner - Integrative Health Coach",
  "Holistic Health Practitioner - Traditional Chinese Medicine (TCM)",
  "Holistic Health Practitioner - Functional Medicine Practitioner",
  "Holistic Health Practitioner - Ayurvedic Practitioner",
  "Holistic Health Practitioner - Energy Healing (Reiki, Healing Touch)",
  "Holistic Health Practitioner - Aromatherapist",
  "Holistic Health Practitioner - Reflexologist",
  "Holistic Health Practitioner - Iridologist",
  "Holistic Health Practitioner - Herbalist",
  "Holistic Health Practitioner - Biofeedback Practitioner",
  "Holistic Health Practitioner - Sound Therapist",
  "Holistic Health Practitioner - Hypnotherapist",

  "Acupuncturist",
  "Dietitian",
  "Nutritionist",
  "Radiologic Technologist",
  "MRI Technologist",
  "Nuclear Medicine Technologist",
  "Respiratory Therapist",
  "Cardiovascular Technologist",
  "Surgical Technologist",
  "Paramedic",
  "EMT (Emergency Medical Technician)",
  "First Responder",
  "Medical Laboratory Technician",
  "Phlebotomist",
  "Clinical Laboratory Scientist",
  "Medical Equipment Supplier",
  "Medical Device Dealer",
  "Ambulance Operator",
  "Medical Transport Driver",
  "Dialysis Technician",
  "Perfusionist",
  "Orthotist",
  "Prosthetist",
  "Genetic Counselor",
  "Marriage and Family Therapist",
  "Licensed Clinical Social Worker",
  "Licensed Professional Counselor",
  "Psychologist",
  "Psychiatrist",
  "Substance Abuse Counselor",
  "Drug & Alcohol Counselor",
  "Behavior Analyst (BCBA)",

  // ── Mental Health & Social Services ──────────────────────────────────────
  "Social Worker",
  "Child Welfare Worker",
  "School Counselor",
  "Mental Health Counselor",
  "Rehabilitation Counselor",
  "Crisis Counselor",

  // ── Childcare & Education ─────────────────────────────────────────────────
  "Childcare Provider",
  "Day Care Operator",
  "Foster Care Provider",
  "Adoption Agency Operator",
  "Youth Camp Operator",
  "Teacher (K-12)",
  "School Principal",
  "School Superintendent",
  "Special Education Teacher",
  "School Bus Driver",
  "Tutor",
  "Private School Operator",
  "Cosmetology School Operator",
  "Vocational School Operator",
  "Driving School Operator",

  // ── Beauty & Personal Services ────────────────────────────────────────────
  "Cosmetologist",
  "Hair Stylist",
  "Barber",
  "Master Barber",
  "Nail Technician",
  "Esthetician",
  "Massage Therapist",
  "Tattoo Artist",
  "Tattoo Studio Operator",
  "Body Piercer",
  "Permanent Makeup Artist",
  "Microblading Technician",
  "Electrologist",
  "Laser Hair Removal Technician",
  "Skin Care Specialist",
  "Waxing Technician",
  "Eyelash Technician",
  "Tanning Salon Operator",

  // ── Animal Care & Veterinary ──────────────────────────────────────────────
  "Veterinarian",
  "Veterinary Technician",
  "Veterinary Assistant",
  "Animal Control Officer",
  "Dog Groomer",
  "Pet Trainer",
  "Dog Trainer",
  "Kennel Operator",
  "Pet Boarding Operator",
  "Farrier",
  "Zookeeper",
  "Zoo Director",
  "Exotic Animal Dealer",
  "Wildlife Rehabilitator",
  "Wildlife Control Operator",
  "Falconer",
  "Horse Trainer",
  "Horse Dealer",
  "Livestock Dealer",
  "Livestock Auctioneer",
  "Brand Inspector",
  "Artificial Insemination Technician",

  // ── Pest Control & Environmental ─────────────────────────────────────────
  "Pest Control Operator",
  "Fumigator",
  "Termite Control Operator",
  "Wildlife Control Operator",
  "Vector Control Specialist",
  "Mosquito Control Operator",
  "Environmental Consultant",
  "Hazardous Waste Handler",
  "Hazardous Waste Transporter",
  "Underground Storage Tank Operator",
  "Asbestos Contractor",
  "Lead Renovation Contractor (RRP)",
  "Radon Mitigation Contractor",
  "Industrial Hygienist",

  // ── Water & Environmental Operations ─────────────────────────────────────
  "Water Treatment Operator",
  "Water Distribution Operator",
  "Drinking Water System Operator",
  "Wastewater Treatment Plant Operator",
  "Stormwater Manager",
  "Swimming Pool Operator",
  "Swimming Pool Inspector",
  "Lifeguard",
  "Well Driller",
  "Well Pump Installer",

  // ── Security & Investigations ─────────────────────────────────────────────
  "Security Guard",
  "Armed Security Guard",
  "Security Manager",
  "Private Security Contractor",
  "Private Investigator",
  "Private Detective",
  "Bail Enforcement Agent (Bounty Hunter)",
  "Repossession Agent",
  "Background Investigator",
  "Insurance Investigator",
  "Workers' Compensation Investigator",
  "Alarm System Installer",
  "CCTV Installer",
  "Access Control Installer",
  "Fire Alarm Installer",
  "Firearm Dealer (FFL)",
  "Firearm Manufacturer",
  "Firearm Repair Technician",
  "Ammunition Dealer",
  "Explosive Technician",
  "Explosive Storage Operator",
  "Armored Car Operator",

  // ── Media, Communications & Broadcasting ─────────────────────────────────
  "Amateur (Ham) Radio Operator",
  "Commercial Radio Operator",
  "Marine Radio Operator",
  "Aviation Radio Operator",
  "Broadcast Technician",
  "Radio Station Operator",
  "Television Station Operator",
  "Cable TV Operator",
  "Telecommunications Carrier",
  "Wireless Carrier Operator",
  "Tower Climber",
  "Antenna Installer",
  "Satellite Installer",
  "Photographer",
  "Commercial Photographer",
  "Drone Photographer",
  "Videographer",
  "Film Production Operator",
  "Motion Picture Operator",

  // ── Funeral & Death Care ──────────────────────────────────────────────────
  "Funeral Director",
  "Embalmer",
  "Crematory Operator",
  "Cemetery Operator",
  "Cemetery Manager",
  "Pre-Need Insurance Seller",
  "Death Care Counselor",

  // ── Mining, Oil & Gas ─────────────────────────────────────────────────────
  "Mine Operator",
  "Mine Safety Inspector",
  "Blaster",
  "Explosives Handler",
  "Oil & Gas Well Driller",
  "Petroleum Engineer",
  "Pipeline Operator",
  "Pipeline Inspector",
  "Storage Tank Inspector",
  "Propane Dealer",
  "Natural Gas Contractor",
  "Gas Fitter",
  "LPG Installer",

  // ── Forestry & Natural Resources ──────────────────────────────────────────
  "Forester",
  "Certified Forester",
  "Timber Harvester",
  "Log Scaler",
  "Sawmill Operator",
  "Hunting Guide",
  "Fishing Guide",
  "Outfitter",
  "Hunting License Dealer",
  "Taxidermist",
  "Fish Hatchery Operator",
  "Trapper",
  "Fur Dealer",

  // ── Retail & Consumer Services ────────────────────────────────────────────
  "Pharmacy Operator",
  "Optometry Practice Operator",
  "Hearing Aid Dispenser",
  "Tattoo Supply Dealer",
  "Secondhand Dealer",
  "Pawnbroker",
  "Precious Metals Dealer",
  "Gem Dealer",
  "Lottery Retailer",
  "Charitable Solicitation Agent",
  "Telemarketer",
  "Health Club Operator",
  "Tanning Facility Operator",
  "Laundry Operator",
  "Dry Cleaner",

  // ── Hospitality & Tourism ─────────────────────────────────────────────────
  "Hotel Operator",
  "Bed & Breakfast Operator",
  "Short-Term Rental Operator",
  "Tour Operator",
  "Travel Agent",
  "Tour Guide",
  "Amusement Park Operator",
  "Carnival Ride Operator",
  "Bingo Hall Operator",
  "Casino Operator",
  "Gambling Device Technician",
  "Sports Wagering Operator",

  // ── Other Licensed Trades ────────────────────────────────────────────────
  "Elevator Constructor (NEIEP)",
  "Nuclear Reactor Operator",
  "Nuclear Power Plant Worker",
  "Polygraph Examiner",
  "Tattoo & Body Art Inspector",
  "Charitable Raffle Operator",
  "Professional Fundraiser",
  "Employment Agency Operator",
  "Staffing Agency Operator",
  "Talent Agency Operator",
  "Modeling Agency Operator",
  "Interpreter",
  "Certified Legal Interpreter",
  "Sign Language Interpreter",

  // ── Knowledge Subjects: Soil & Plant Sciences ─────────────────────────────
  "Soil Science",
  "Soil Physics",
  "Soil Chemistry",
  "Soil Biology",
  "Soil Classification & Survey",
  "Soil Fertility & Management",
  "Agronomy",
  "Crop Science",
  "Weed Science",
  "Crop Protection",
  "Precision Agriculture",
  "Agriculture",
  "Sustainable Agriculture",
  "Irrigation Management",
  "Agricultural Economics",
  "Farm Management",

  // ── Knowledge Subjects: Natural Sciences ──────────────────────────────────
  "Biology",
  "Cell Biology",
  "Genetics",
  "Ecology",
  "Microbiology",
  "Anatomy & Physiology",
  "Physics",
  "Classical Mechanics",
  "Thermodynamics",
  "Electromagnetism",
  "Optics",
  "Modern Physics",
  "Chemistry",
  "Organic Chemistry",
  "Analytical Chemistry",
  "Biochemistry",
  "Physical Chemistry",
  "Astronomy",
  "Solar System Astronomy",
  "Stars & Galaxies",
  "Cosmology",
  "Observational Astronomy",
  "Mathematics",
  "Algebra",
  "Geometry",
  "Trigonometry",
  "Calculus",
  "Statistics & Probability",

  // ── Knowledge Subjects: Accounting ────────────────────────────────────────
  "Accounting",
  "Financial Accounting",
  "Managerial Accounting",
  "Taxation",
  "Auditing",
  "Cost Accounting",

  // ── Knowledge Subjects: Animal Science ────────────────────────────────────
  "Animal Science",
  "Companion Animal Science",
  "Livestock Science",
  "Equine Science",
  "Avian & Poultry Science",
  "Exotic & Wildlife Science",

];

// Subjects that use knowledge/reference-based generation rather than law enumeration.
// When any selected trade is in this set, the generation pipeline adapts to enumerate
// references, standards, textbook chapters, and professional certification requirements
// instead of (or in addition to) laws.
export const KNOWLEDGE_SUBJECTS = new Set([
  "Soil Science", "Soil Physics", "Soil Chemistry", "Soil Biology", "Soil Classification & Survey", "Soil Fertility & Management",
  "Agronomy", "Crop Science", "Weed Science", "Crop Protection", "Precision Agriculture",
  "Agriculture", "Sustainable Agriculture", "Irrigation Management", "Agricultural Economics", "Farm Management",
  "Biology", "Cell Biology", "Genetics", "Ecology", "Microbiology", "Anatomy & Physiology",
  "Physics", "Classical Mechanics", "Thermodynamics", "Electromagnetism", "Optics", "Modern Physics",
  "Chemistry", "Organic Chemistry", "Analytical Chemistry", "Biochemistry", "Physical Chemistry",
  "Astronomy", "Solar System Astronomy", "Stars & Galaxies", "Cosmology", "Observational Astronomy",
  "Mathematics", "Algebra", "Geometry", "Trigonometry", "Calculus", "Statistics & Probability",
  "Accounting", "Financial Accounting", "Managerial Accounting", "Taxation", "Auditing", "Cost Accounting",
  "Animal Science", "Companion Animal Science", "Livestock Science", "Equine Science", "Avian & Poultry Science", "Exotic & Wildlife Science",
  "Farrier",
]);